version: '2'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    command: yarn dev
    ports:
      - "8082:8082"
    env_file: .env
    volumes:
      - ./:/webpack-boilerplate